In [4]:
import numpy as np

print(np.arange(0, 10, 2))
print()
print((np.zeros(3)))
print()
print(np.ones((5, 5)))

[0 2 4 6 8]

[0. 0. 0.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
print(np.linspace(0, 10, 4))  # start, stop, how many elements

[ 0.          3.33333333  6.66666667 10.        ]


In [9]:
print(np.random.rand(2))  # random distribution from 0 to 1
print(np.random.randn(2)) # generates elements from normal distribution

[0.47052231 0.47057365]
[-0.57000585  0.3018661 ]


In [12]:
alist = [
    [11, 12, 13],
    [21, 22, 23],
]

print(alist)
print(f'21: {alist[1][0]}')

[[11, 12, 13], [21, 22, 23]]
21: 21


In [14]:
import numpy as np

arr = np.array([
    [11, 12, 13],
    [21, 22, 23],
])

arr

array([[11, 12, 13],
       [21, 22, 23]])

In [15]:
print(f'21 from array: {arr[1, 0]}')

21 from array: 21


In [16]:
print(f'21 from array: {arr[1][0]}')

21 from array: 21


In [17]:
a1 = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a1[1, ::-1]

array([7, 6, 5, 4])

In [25]:
a1 = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])
print(a1.T)
print(a1)
a1T = np.transpose(a1)
print(a1T)
print(a1)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a3 = np.array([
    [
        [111, 112],
        [211, 212]
    ],
    
])[]

In [26]:
import numpy as np

arr = np.array([
    [11, 12, 13],
    [21, 22, 23],
])

arr + 100

array([[111, 112, 113],
       [121, 122, 123]])

In [28]:
arr1 = np.array([
    [11, 12, 13],
    [21, 22, 23]
])
print(arr1)

arr2 = np.array([11, 12, 13])
print(arr2)

arr3 = arr1 + arr2
arr3

[[11 12 13]
 [21 22 23]]
[11 12 13]


array([[22, 24, 26],
       [32, 34, 36]])

In [29]:
arr1 = np.array([
    [11, 12, 13],
    [21, 22, 23]
])
print(arr1)

arr2 = np.array([11, 12])
print(arr2)

arr3 = arr1 + arr2
arr3

[[11 12 13]
 [21 22 23]]
[11 12]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [36]:
arr2 = np.array([11, 12, 14])
print(arr2 > 12)
print(arr2[arr2 > 12])

[False False  True]
[14]


In [34]:
print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [38]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [39]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [40]:
a3[0,1,:]

array([3, 4, 5])