In [4]:
import numpy as np

print(np.arange(0, 10, 2))
print()
print((np.zeros(3)))
print()
print(np.ones((5, 5)))

[0 2 4 6 8]

[0. 0. 0.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
print(np.linspace(0, 10, 4))  # start, stop, how many elements

[ 0.          3.33333333  6.66666667 10.        ]


In [9]:
print(np.random.rand(2))  # random distribution from 0 to 1
print(np.random.randn(2)) # generates elements from normal distribution

[0.47052231 0.47057365]
[-0.57000585  0.3018661 ]
